name: Workflow-CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CSV_URL: "MLproject/dataset_preprocessing.csv"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository
      - name: Run actions/checkout@v3
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.TOKEN_WORKFLOW }}

      # Setup Python
      - name: Set up Python 3.12.7
        uses: actions/setup-python@v4
        with:
          python-version: "3.12.7"

      # Check Env
      - name: Check Env
        run: |
          echo $CSV_URL

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mlflow

      # Run ML project
      - name: Run MLflow project
        run: |
          mlflow run MLproject --env-manager=local

      # Get latest MLflow run_id
      - name: Get latest MLflow run_id
        run: |
          RUN_ID=$(ls -td MLproject/mlruns/0/*/ | head -n 1 | cut -d'/' -f4 || echo "")
          echo "RUN_ID=$RUN_ID" >> $GITHUB_ENV
          echo "Latest run_id: $RUN_ID"
